fix: error in prod deployment
Error: [vite]: Rollup failed to resolve import "@mantine/hooks" from
"/opt/render/project/src/node_modules/@mantine/core/esm/Alert/Alert.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`